version: '3.8'

services:
  redis_server:
    image: redis:latest
    container_name: auth_gateway_242_grpc

    ports:
      - 6379:6379

  auth_gateway_242_http:
    image: auth_gateway_img:latest
    command: sh -c "python3 http_server.py"
    depends_on:
      - redis-server

    environment:
      - auth_gateway_env=.server.env

    volumes:
      - ./log:/var/log
    container_name: auth_gateway_242_http

    ports:
      - 3001:3000

  auth_gateway_242_grpc:
    image: auth_gateway_img:latest
    command: sh -c "python3 grpc_server.py"
    depends_on:
      - redis-server

    environment:
      - auth_gateway_env=.server.env

    volumes:
      - ./log:/var/log

    container_name: auth_gateway_242_grpc

    ports:
      - 50056:50056

